# CSV types (txt files)
const GTFS_TYPES = Dict{Symbol, Type}(
    :ID => Union{String, Missing},
    :Enum => Union{Int64, Missing},
    :Timezone => Union{String, Missing},
    :Date => Union{String, Missing},
    :Time => Union{String, Missing},
    :LocalTime => Union{String, Missing},
    :Latitude => Union{Float64, Missing},
    :Longitude => Union{Float64, Missing},
    :Float => Union{Float64, Missing},
    :Integer => Union{Int64, Missing},
    :Text => Union{String, Missing},
    :String => Union{String, Missing},
    :Email => Union{String, Missing},
    :PhoneNumber => Union{String, Missing},
    :URL => Union{String, Missing},
    :LanguageCode => Union{String, Missing},
    :CurrencyCode => Union{String, Missing},
    :CurrencyAmount => Union{String, Missing},
    :Color => Union{String, Missing},
    :Array => Union{Vector{String}, Missing},
    :Object => Union{Dict{String, Any}, Missing},
)
